import type { NextPage } from "next";
import Head from "next/head";
import axios from "axios";
import useSWR from "swr";
import { Suspense } from "react";
const api = axios.create({
  baseURL: "https://backend-planus.herokuapp.com",
});
const fetcher = (url: string) => api.get(url).then((res) => res.data);

const useFetch = <T extends Object>(url: string) => {
  const { data, error, mutate } = useSWR<T>(url, fetcher, { suspense: true });

  const loading = !data && !error;
  return { data, error, mutate, loading };
};

const HomeNacked = () => {
  const { ...request } = useFetch<{ healthy: boolean }>("health");
  const { ...request1 } = useFetch<{ healthy: boolean }>("health");
  const { ...request2 } = useFetch<{ healthy: boolean }>("health");

  console.log({ request: request, request1: request1, request2: request2 });
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <div>{request.data && JSON.stringify(request.data)}</div>

        <button onClick={() => request.mutate()}>Mutate</button>
   
    </div>
  );
};


const Home: NextPage = () => {
  return (

      <Suspense fallback={<div>loading...</div>}>
        <HomeNacked/>
      </Suspense>
  );
};

export default Home;
