name: Increment vertion
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: :obra_prédio: Setup repo
        uses: actions/checkout@v2
      - name: :obra_prédio: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
      - name: :pacote: Install dependencies
        run: yarn install
      - name: :pacote: Increment version
        run: yarn release
